# Site Settings
title: Conception et évaluation de tableaux de bord d’apprentissage
subtitle: "Atelier RJC-EIAH 2022"
email: madjid.sadallah@gmail.com
description: >
  
baseurl: "https://padlad.github.io/RJC-EIAH2022"
url: "https://padlad.github.io/RJC-EIAH2022"
twitter_username: smadjid
github_username:  smadjid
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
