# Site Settings
title: Visualiser des indicateurs de compétences - objectifs et verrous
subtitle: "Atelier EIAH 2025"
email: jm.gilliot@imt-atlantique.fr
description: >
  
baseurl: "https://padlad.github.io/EIAH2025"
url: "https://padlad.github.io/EIAH2025"
twitter_username: jmgilliot
github_username:  jmgilliot
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
